### PR TITLE
Create fr.json

### PR DESCRIPTION
**Pull request by YashovardhanSingh**
French Translation

### CODE REVIEW

**Comment by YashovardhanSingh** [comment]
853cf2c5353f1fe403672611725480dd55e6424660212924a8d60b38fdaff4a0

**Comment by mrbusysky** [comment]
What are you using to translate these?

**Comment by YashovardhanSingh** [comment]
I am using Google Translate, Translate.com, and also https://www.deepl.com/en/translator (best one) together and translating every word of the sentence if any confusion. Also, I have the basic knowledge of these languages as I have learned them before.

**Comment by mrbusysky** [comment]
Google translate isn't allowed

**Pull request closed without merging**
