### PR TITLE
Add Arabic localization

### PR DESCRIPTION
**Pull request by hayderkharrufa**
Account Number:    7a42c9cfc4d0f0d2ba5fe126a712f5bbe8ce20d002d427b48f7490b074b9f361

Please keep in mind that Arabic is written right to left (RTL).

### CODE REVIEW

**Comment by mrbusysky** [comment]
Done editing?

**Comment by hayderkharrufa** [comment]
> Done editing?

Yes

**Comment by mrbusysky** [comment]
paid

**Comment by mrbusysky** [comment]
> > Done editing?
> 
> Yes

Would you be willing to make some edits to the translations? We made some edits to the English file that now no longer match the current translations.

**Comment by hayderkharrufa** [comment]
> > > Done editing?
> > 
> > 
> > Yes
> 
> Would you be willing to make some edits to the translations? We made some edits to the English file that now no longer match the current translations.

Yes sure. I just read your message.
I will wait for the app to get approved on Play Store so I can test it and be able to provide more accurate translations.

**Pull request merged**
